import type { Recipe } from './types';

export const sampleRecipes: Recipe[] = [
  {
    id: '1',
    title: 'Паста Карбонара',
    description: 'Классическая итальянская паста с яйцами, сыром пекорино и гуанчиале',
    category: 'meat',
    image: 'https://images.unsplash.com/photo-1612874742237-6526221588e3?w=800&q=80',
    video: 'https://player.vimeo.com/external/499415519.sd.mp4?s=dabb0f3f327c7c9e6a1c5e0c8e0c8e0c8e0c8e0c&profile_id=164&oauth2_token_id=57447761',
    ingredients: [
      { id: '1', name: 'Спагетти', amount: '400 г', checked: false },
      { id: '2', name: 'Гуанчиале (или панчетта)', amount: '200 г', checked: false },
      { id: '3', name: 'Яйца', amount: '4 шт', checked: false },
      { id: '4', name: 'Сыр пекорино романо', amount: '100 г', checked: false },
      { id: '5', name: 'Чёрный перец', amount: 'по вкусу', checked: false },
    ],
    steps: [
      'Нарежьте гуанчиале небольшими кубиками и обжарьте на сковороде до хрустящей корочки.',
      'Смешайте яйца с натёртым сыром и чёрным перцем в отдельной миске.',
      'Отварите спагетти до состояния аль денте в подсоленной воде.',
      'Сохраните немного воды от пасты, затем переложите пасту в сковороду с гуанчиале.',
      'Снимите сковороду с огня, добавьте яичную смесь и быстро перемешайте.',
      'При необходимости добавьте немного воды от пасты для нужной консистенции.',
    ],
    prepTime: 10,
    cookTime: 15,
    servings: 4,
    createdAt: Date.now(),
  },
  {
    id: '2',
    title: 'Круассаны',
    description: 'Воздушные французские круассаны с хрустящими слоями',
    category: 'bakery',
    image: 'https://images.unsplash.com/photo-1555507036-ab1f40388085?w=800&q=80',
    ingredients: [
      { id: '1', name: 'Мука высшего сорта', amount: '500 г', checked: false },
      { id: '2', name: 'Сливочное масло', amount: '300 г', checked: false },
      { id: '3', name: 'Молоко', amount: '250 мл', checked: false },
      { id: '4', name: 'Дрожжи свежие', amount: '25 г', checked: false },
      { id: '5', name: 'Сахар', amount: '50 г', checked: false },
      { id: '6', name: 'Соль', amount: '10 г', checked: false },
    ],
    steps: [
      'Приготовьте тесто из муки, молока, дрожжей, сахара и соли. Замесите до однородности.',
      'Раскатайте тесто в прямоугольник и выложите слой охлаждённого сливочного масла.',
      'Сложите тесто в три слоя, заверните в плёнку и охладите 30 минут.',
      'Повторите процесс раскатки и складывания 3-4 раза, охлаждая между подходами.',
      'Раскатайте тесто, нарежьте треугольники и скрутите в форме круассанов.',
      'Дайте подняться 2 часа, затем выпекайте при 180°C 15-20 минут.',
    ],
    prepTime: 60,
    cookTime: 20,
    servings: 12,
    createdAt: Date.now() - 100000,
  },
  {
    id: '3',
    title: 'Авокадо-тост',
    description: 'Полезный завтрак с авокадо, яйцом пашот и семенами чиа',
    category: 'breakfast',
    image: 'https://images.unsplash.com/photo-1588137372308-15f75323ca8d?w=800&q=80',
    video: 'https://player.vimeo.com/external/370331493.sd.mp4?s=e90dcaba73c19e0e36f03406b47bbd6992dd6c1c&profile_id=139&oauth2_token_id=57447761',
    ingredients: [
      { id: '1', name: 'Хлеб цельнозерновой', amount: '2 ломтика', checked: false },
      { id: '2', name: 'Авокадо спелый', amount: '1 шт', checked: false },
      { id: '3', name: 'Яйца', amount: '2 шт', checked: false },
      { id: '4', name: 'Лимонный сок', amount: '1 ст. ложка', checked: false },
      { id: '5', name: 'Семена чиа', amount: '1 ч. ложка', checked: false },
      { id: '6', name: 'Соль, перец', amount: 'по вкусу', checked: false },
    ],
    steps: [
      'Поджарьте ломтики хлеба до золотистой корочки.',
      'Разомните авокадо вилкой, добавьте лимонный сок, соль и перец.',
      'Приготовьте яйца пашот: варите в кипящей воде с уксусом 3 минуты.',
      'Намажьте тосты пюре из авокадо, сверху выложите яйцо пашот.',
      'Посыпьте семенами чиа и добавьте по вкусу соль и перец.',
    ],
    prepTime: 5,
    cookTime: 10,
    servings: 2,
    createdAt: Date.now() - 200000,
  },
  {
    id: '4',
    title: 'Тирамису',
    description: 'Нежный итальянский десерт с маскарпоне и кофе',
    category: 'dessert',
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=800&q=80',
    ingredients: [
      { id: '1', name: 'Сыр маскарпоне', amount: '500 г', checked: false },
      { id: '2', name: 'Печенье савоярди', amount: '200 г', checked: false },
      { id: '3', name: 'Кофе эспрессо', amount: '300 мл', checked: false },
      { id: '4', name: 'Яйца', amount: '4 шт', checked: false },
      { id: '5', name: 'Сахар', amount: '100 г', checked: false },
      { id: '6', name: 'Какао-порошок', amount: 'для посыпки', checked: false },
    ],
    steps: [
      'Приготовьте кофе эспрессо и остудите до комнатной температуры.',
      'Отделите белки от желтков. Взбейте желтки с сахаром до пышности.',
      'Добавьте маскарпоне к желткам и аккуратно перемешайте.',
      'Взбейте белки до устойчивых пиков и осторожно введите в крем.',
      'Обмакивайте печенье в кофе и выкладывайте слоями в форму.',
      'Чередуйте слои печенья и крема. Охладите минимум 4 часа.',
      'Перед подачей посыпьте какао-порошком.',
    ],
    prepTime: 30,
    cookTime: 0,
    servings: 8,
    createdAt: Date.now() - 300000,
  },
  {
    id: '5',
    title: 'Борщ украинский',
    description: 'Традиционный свекольный суп с насыщенным вкусом',
    category: 'soup',
    image: 'https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80',
    video: 'https://player.vimeo.com/external/371835647.sd.mp4?s=4925450b5beefe15eb20d4fb5752a80c05ae5464&profile_id=139&oauth2_token_id=57447761',
    ingredients: [
      { id: '1', name: 'Говядина на кости', amount: '500 г', checked: false },
      { id: '2', name: 'Свёкла', amount: '2 шт', checked: false },
      { id: '3', name: 'Капуста белокочанная', amount: '300 г', checked: false },
      { id: '4', name: 'Картофель', amount: '3 шт', checked: false },
      { id: '5', name: 'Морковь', amount: '1 шт', checked: false },
      { id: '6', name: 'Лук', amount: '1 шт', checked: false },
      { id: '7', name: 'Томатная паста', amount: '2 ст. ложки', checked: false },
    ],
    steps: [
      'Сварите бульон из говядины, остудите и процедите.',
      'Натрите свёклу на тёрке, обжарьте с томатной пастой и уксусом.',
      'Нарежьте капусту соломкой, картофель кубиками.',
      'Выложите в бульон картофель и капусту, варите 15 минут.',
      'Добавьте обжаренные свёклу и овощи.',
      'Варите до готовности, приправьте чесноком и зеленью.',
    ],
    prepTime: 20,
    cookTime: 120,
    servings: 6,
    createdAt: Date.now() - 400000,
  },
  {
    id: '6',
    title: 'Стейк Рибай',
    description: 'Сочный мраморный стейк с пряными травами',
    category: 'meat',
    image: 'https://images.unsplash.com/photo-1600891964092-4316c288032e?w=800&q=80',
    video: 'https://player.vimeo.com/external/422378661.sd.mp4?s=548274892804060081105274412545576246&profile_id=164&oauth2_token_id=57447761',
    ingredients: [
      { id: '1', name: 'Стейк рибай', amount: '400 г', checked: false },
      { id: '2', name: 'Сливочное масло', amount: '50 г', checked: false },
      { id: '3', name: 'Чеснок', amount: '3 зубчика', checked: false },
      { id: '4', name: 'Тимьян свежий', amount: 'несколько веточек', checked: false },
      { id: '5', name: 'Морская соль', amount: 'по вкусу', checked: false },
      { id: '6', name: 'Чёрный перец', amount: 'по вкусу', checked: false },
    ],
    steps: [
      'Достаньте стейк из холодильника за 30 минут до готовки.',
      'Нагрейте сковороду до сильного жара, посолите и поперчите стейк.',
      'Обжаривайте по 3-4 минуты с каждой стороны для medium-rare.',
      'Добавьте масло, чеснок и тимьян, поливайте стейк маслом.',
      'Перенесите стейк на тарелку, дайте отдохнуть 5 минут.',
    ],
    prepTime: 35,
    cookTime: 10,
    servings: 2,
    createdAt: Date.now() - 500000,
  },
];
